[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp']
hook_add = '''
    let g:clang_format#style_options = {
        \ "BasedOnStyle" : "Google"}
    let g:clang_format#auto_format = 1
    autocmd FileType c,cpp,objc map <buffer><Leader>f <Plug>(operator-clang-format)'''

[[plugins]]
repo = 'kana/vim-operator-user'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
hook_post_source = '''
call lexima#add_rule({'at':'\%#.*[-0-9a-zA-Z_,:]','char':'{','input':'{'})
call lexima#add_rule({'at':'\%#.*[-0-9a-zA-Z_,:]','char':'(','input':'('})
call lexima#add_rule({'at':'\%#.*[-0-9a-zA-Z_,:]','char':'[','input':'['})
call lexima#add_rule({'at':'\%#.*[-0-9a-zA-Z_,:]','char':'"','input':'"'})
call lexima#add_rule({'at': '\%#.*[-0-9a-zA-Z_,:]', 'char': "'", 'input': "'"})
'''

