[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp', 'h']
hook_add = '''
    let g:clang_format#style_options = {
        \ "BasedOnStyle" : "Google"}
    let g:clang_format#auto_format = 1
    autocmd FileType c setlocal sw=2 sts=2 ts=2 et
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
hook_post_source = '''
call lexima#add_rule({'at':'\%#.*[-0-9a-zA-Z_,:]','char':'{','input':'{'})
call lexima#add_rule({'at':'\%#.*[-0-9a-zA-Z_,:]','char':'(','input':'('})
call lexima#add_rule({'at':'\%#.*[-0-9a-zA-Z_,:]','char':'[','input':'['})
call lexima#add_rule({'at':'\%#.*[-0-9a-zA-Z_,:]','char':'"','input':'"'})
call lexima#add_rule({'at': '\%#.*[-0-9a-zA-Z_,:]', 'char': "'", 'input': "'"})
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-clang'
hook_source ='''
  let g:deoplete#sources#clang#libclang_path='/usr/local/opt/llvm/lib/libclang.dylib'
  let g:deoplete#sources#clang#clang_header='/usr/local/opt/llvm/lib/clang'
'''
on_ft = ['c', 'cpp', 'cmake', 'h']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'zchee/deoplete-jedi'
hook_source = '''
  let g:deoplete#sources#jedi#server_timeout = 20
  let g:deoplete#sources#jedi#python_path='/usr/local/bin/python3'
'''
on_ft = 'python'

# [[plugins]]
# repo = "OmniSharp/omnisharp-vim"
# on_ft = ["cs"]
# build = "xbuild server/OmniSharp.sln"

# [[plugins]]
# repo = "Robzz/deoplete-omnisharp"
# on_source = ["deoplete.nvim"]
